### ISSUE TITLE
Välipalautus 3 vertaisarviointi

### ISSUE THREAD

**Issue by Cloudperry** [ElectricShakuhachi/tietokantasovellus-shakuarchive#1]
Sovellus toimi vielä maanantaina, kun kävin pikaisesti vilkaisemassa sitä herokussa, mutta tällä hetkellä se antaa virhettä "Internal server error". Testasin sovellusta paikallisesti, mutta paikallisessa versiossa sain pelkän tilien luonnin, sisäänkirjautumisen ja etusivun toimimaan. Tämä arvio keskittyy siis lähinnä sovelluksen koodiin ja mainittuihin toimiviin ominaisuuksiin.

## Käyttöliittymä
Etusivu on ihan kivan näköinen ja sisäänkirjautuminen heti etusivulla on melko kätevä ominaisuus. Nappi rekisteröitymistä varten on ehkä hieman hämäävässä paikassa ja liian samankaltainen sisäänkirjautumisnapin kanssa. Siitä voisi jopa luulla, että nappi käyttää yllä olevia tekstikenttiä tilin luomiseen. Napin voisi muuttaa tavalliseksi linkiksi, jotta se ei olisi hämäävä. Toinen vaihtoehto voisi olla jonkinlaisen tab valikon lisääminen harmaan pyöristetyn laatikon yläreunaan, joka vaihtaa laatikon lomakkeen rekisteröitymislomakkeeksi. Sisäänkirjautumislomakkeen tekstit ovat vähän oudoissa paikoissa. Tekstit voisi laittaa molemmpien kenttien yläpuolelle tai vasemmalle. Sisäänkirjautumisnapin voisi myös siirtää koko lomakkeen alapuolelle tai samaan kohtaan kuin rekisteröitymislomakkeessa. Sivu jolla nuotteja/kappaleita ladataan on hyvä. Sitä voisi parantaa siirtämällä kenttien kuvaukset lähemmäs kenttiä. Kappaleiden lajittelua olisi mahdollista tehdä helpommaksi, jos notation kentän sallitut arvot olisi dropdown valikossa.

## Ominaisuuksien toimivuus
Sisäänkirjautuminen ja rekisteröinti toimii hyvin. Virheet ilmoitetaan selvästi samalla sivulla, jolla virhe on tapahtunut. Lista sovellukseen ladatuista kappaleista toimi Herokussa maanantaina, mutta en saanut sitä toimimaan paikallisesti, koska se käyttää AWS:ää.

## Tietokannan rakenne ja schema.sql
Tietokannan schema.sql tiedostossa voisi luettavuuden parantamiseksi laittaa taulun kentät omille riveilleen. Tietokannan rakenne vaikuttaisi olevan muuten hyvä, mutta viittaukset muihin tauluihin kannattaisi merkitä erikseen ("uploader TEXT" sijasta "uploader INT REFERENCES users"). Jos kappaleen lataajan nimi täytyy säilyttää, vaikka käyttäjä poistaisi tilinsä, voi tauluun users lisätä poistettu sarakkeen. Lisäksi id saraketta ei välttämättä tarvittaisi tauluissa, joihin muut taulut eivät viittaa (compositions ja genres). Tämä on ehkä hiemän ylimääräistä, mutta kaikkiin pakollisiin kenttiin voisi lisätä NOT NULL merkinnän, jotta tietokanta ei sallisi rivien lisäämistä, joilta puuttuu jokin pakollinen kenttä. 

## Sovelluksen kansiorakenne ja koodi
Sovellus on yhdessä tiedostossa ja tällä hetkellä se ei haittaa kovin paljon, koska koodia on vajaa 200 riviä. Sovelluksen koodi kannattaisi jakaa vähintään kahteen tiedostoon, jos siihen on vielä tulossa lisää ominaisuuksia. Jaon voisi alottaa esim. siitä, että tietokannan, Flaskin ja boto3:n alustus tehdään init.py:ssä ja kaikki muu app.py:ssä. Nyt boto3 client alustetaan ja konfiguroidaan jatkuvasti uudestaan.

Koodi on selkeää ja muuttujat on nimetty hyvin. Käyttäjätiliä luodessa käytetty salasanan tarkistus on toteutettu hieman oudolla tavalla, mutta muuten en muuttaisi juuri mitään.

**Comment by ElectricShakuhachi** [comment]
Hei - kiitos arvioinnista ja hyvistä ohjeista. En tullut ajatelleeksi vertaisarviointia kun tulin tyhjentäneeksi tietokannan aivan uutta skeemaa varten jo ennen kun olin valmis uuden skeeman kanssa, joten herokussa oleva versio ei tietty toiminut kun sillä ei ollut tietokantatauluja.
